#server {
#    listen 80;
#    server_name bstock-dev;
#
#    # 自動將 HTTP 重定向到 HTTPS
#    location / {
#        return 301 https://$host:8443$request_uri;
#    }
#}

server {
    listen 443 ssl;
    server_name bstock-dev;

    # SSL 憑證與私鑰
    ssl_certificate /etc/nginx/certs/mycert.crt;
    ssl_certificate_key /etc/nginx/certs/mykey.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://bigstock-gateway:11081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}