server:
  port: 10093    
  oauth2:
    secret-key: 4903837210390382930293802938293802932038203920382039203820392038
    key: classpath:jwt.pem
  registry-verify-url: ${SERVER_REGISTRY_VERIFY_RUL}
spring:
  main: 
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: bigstock-auth
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    virtual-host: /
    pool:
      channelCacheSize: 5   
  cloud:
    consul:
      host: ${SPRING_CONSUL_HOST}
      port: ${SPRING_CONSUL_PORT}    
  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
    timeout: 5000
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
  sleuth:
    sampler:
      probability: 1.0      
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    from: ${SPRING_MAIL_FROM}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST}    
logging:
  config: classpath:logback.xml
  
springdoc:
  api-docs:
    path: /auth/swagger/v3/api-docs   
  swagger-ui:
    path: /auth/swagger/swagger-ui.html  
    enable: true  
    
    
    
management:
  endpoints:
    web:
      exposure:
        include: "*" # 包含所有的Actuator端点，可以根据需要进行调整
  endpoint:
    health:
      show-details: always
  health:
    consul:
      enabled: true  
  tracing:
    enabled: true
    sampling:
      probability: ${OPENTRACING_JAEGER_SAMPLER_PARAM}  
    export:
      otlp:
        enabled: true
        endpoint: ${OPENTRACING_JAEGER_HTTP-SENDER_URL}  # Jaeger 的 OTLP 接收端点    
