server:
  port: 18081
  shutdown: graceful
spring:
  application:
    name: bigstock-schedule
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      host: ${SPRING_CONSUL_HOST}
      port: ${SPRING_CONSUL_PORT} 
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true  
  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
    lettuce:
      pool:
        max-active: 200
        max-idle: 500
        min-idle: 10
        max-wait: 100000
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    virtual-host: /
    pool:
      channelCacheSize: 5          
logging:
  config: classpath:logback.xml

schedule:
  bpython-url: ${SCHEDULE_BPYTHON_URL}
  credentials-pathl: ${SCHEDULE_CREDENTIALS-PATHL}
  task:
    scheduling:
      cron:
        expression: 
          grasp-stock-price: "0 0 20 ? * *"
          grasp-securitiesfirms-dayoperate: "0 0 17 ? * *"
          update-shareholder-structure: "0 0 8 ? * SUN"
          update-stock-info: "0 0 8 ? * SAT"
          sync-start-date: 20240606
  chromeDriverPath:
    windows: 
      active: false	
      path: D:/sts/chromedriver-win64/chromedriver.exe
    linux:
       active: true
       driver-path: ${CHROME_DRIVER_LINUX_PATH}
     #  chrome-path: ${CHROME_DRIVER_LINUX_PATH}	
    download-path: ${CHROME_DOWNLOAD_PATH}
  tdccQryStockUrl: https://www.tdcc.com.tw/portal/zh/smWeb/qryStock
  overTheCounterUrl: https://mops.twse.com.tw/mops/web/t51sb01
  stock-price:
    url:
      tpex: https://www.tpex.org.tw/web/stock/aftertrading/daily_close_quotes/stk_quote_result.php?l=zh-tw&d={dateString}&s=asc
      twse: https://www.twse.com.tw/pcversion/zh/exchangeReport/MI_INDEX
  manual-date-range:
    tpex-baseurl: https://www.tpex.org.tw/web/stock/aftertrading/daily_trading_info/st43_result.php?l=zh-tw&d=%1s&stkno=%2s&_=17225  
    twse-baseurl: https://www.twse.com.tw/exchangeReport/STOCK_DAY?response=json&date=%1s&stockNo=%2s&_=16481  
management:
  endpoints:
    web:
      exposure:
        include: "*" # 包含所有的Actuator端点，可以根据需要进行调整
  endpoint:
    health:
      show-details: always
  health:
    consul:
      enabled: true  
  tracing:
    enabled: true
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY}  # 设置采样率为 100%
    export:
      otlp:
        enabled: true
        endpoint: ${MANAGEMENT_TRACING_EXPORT_ENDPOINT}  # Jaeger 的 OTLP 接收端点          
tracing:
  url: ${TRACING_URL}   
