server:
  port: 18080
  shutdown: graceful

#  ssl:
#    enabled: false
#    key-store: classpath:container-sit.testesunbank.com.tw.jks
#    key-store-password: ENC(KXcrgSoHASfYwGk2mmH8sRwkr4+DHY/kez+vPE0Pz2pRoYGWMjqw+r1eVs/41i6m)
#    key-store-type: JKS
spring: 
  application:
    name: bigstock-schedule
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true   
  redis:
    host: ${SPRING_REDIS_HOST}
    lettuce:
      pool:
        max-active: 200
        max-idle: 500
        min-idle: 10
        max-wait: 100000
    port: ${SPRING_REDIS_PORT}   
            
logging:
  config: classpath:logback.xml
  
springdoc:
  api-docs:
    path: /schedule/swagger/v3/api-docs  
  swagger-ui:
    path: /schedule/swagger/swagger-ui.html  
schedule:
  bpython-url: ${SCHEDULE_BPYTHON_URL}
  credentials-pathl: ${SCHEDULE_CREDENTIALS-PATHL}
  task:
    scheduling:
      cron:
        expression: 
          grasp-stock-price: "0 30 8 * * *"
          grasp-securitiesfirms-dayoperate: "0 30 8 * * *"
          update-shareholder-structure: "0 30 8 * * *"
          update-stock-info: "0 30 8 * * *"
          update-margin-trading: "0 30 8 * * *"
          update-threeInsti: "0 30 18 * * *"
          update-monthlyRevenue: "0 0 8 * * SUN"
  chromeDriverPath:
    windows: 
      active: false	
      path: D:/sts/chromedriver-win64/chromedriver.exe
    linux:
       active: true
       driver-path: ${CHROME_DRIVER_LINUX_PATH}
     #  chrome-path: ${CHROME_DRIVER_LINUX_PATH}	
    download-path: ${CHROME_DOWNLOAD_PATH}
  tdccQryStockUrl: https://www.tdcc.com.tw/portal/zh/smWeb/qryStock
  overTheCounterUrl: https://mops.twse.com.tw/mops/web/t51sb01
  manual-date-range:
    tpex-baseurl: https://www.tpex.org.tw/web/stock/aftertrading/daily_trading_info/st43_result.php?l=zh-tw&d=%1s&stkno=%2s&_=17225  
    twse-baseurl: https://www.twse.com.tw/exchangeReport/STOCK_DAY?response=json&date=%1s&stockNo=%2s&_=16481  
    search-start-date: 2024-05-05
    search-end-date: 2024-11-05    
