apiVersion: zeabur.com/v1
kind: Template

metadata:
  name: bigstock-biz

spec:
  description: BigStock Backend Service

  services:
    - name: redis
      template: PREBUILT
      spec:
        source:
          image: redis:7.2.4

        ports:
          - id: redis
            port: 6379
            type: TCP

        volumes:
          - id: redis-data
            dir: /data  

        command:
          - redis-server
          - --dir
          - /data
          - --appendonly
          - "yes"