server:
  port: 18080
  shutdown: graceful
  ssl:
    enabled: false
    key-store: classpath:container-sit.testesunbank.com.tw.jks
    key-store-password: ENC(KXcrgSoHASfYwGk2mmH8sRwkr4+DHY/kez+vPE0Pz2pRoYGWMjqw+r1eVs/41i6m)
    key-store-type: JKS
  servlet:
    context-path: /api
spring:
  application:
    name: big-stcok-backend-biz
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres??currentSchema=bstock
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
  redis:
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 200
        max-idle: 500
        min-idle: 10
        max-wait: 100000
    port: 6379      
#logging:
#  config: classpath:log4j2.xml

