global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:9090']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']  # 使用 Jaeger 暴露的 9090 端口    