server:
  port: 10093    
  oauth2:
    secret-key: 4903837210390382930293802938293802932038203920382039203820392038
    key: classpath:jwt.pem
spring:
  main: 
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: bigstock-auth
  consul:
    host: ${SPRING_CONSUL_HOST}
    port: ${SPRING_CONSUL_PORT}    
  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
    timeout: 5000
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true

logging:
  config: classpath:logback.xml