server:
  port: 10093    
  oauth2:
    secret-key: 4903837210390382930293802938293802932038203920382039203820392038
    key: classpath:jwt.pem
spring:
  main: 
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: big-stock-auth-server
  consul:
    host: 127.0.0.1
    port: 8500    
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres??currentSchema=bstock
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true

logging:
  config: classpath:logback.xml