server:
  port: 18080
  shutdown: graceful
#  ssl:
#    enabled: false
#    key-store: classpath:container-sit.testesunbank.com.tw.jks
#    key-store-password: ENC(KXcrgSoHASfYwGk2mmH8sRwkr4+DHY/kez+vPE0Pz2pRoYGWMjqw+r1eVs/41i6m)
#    key-store-type: JKS
spring: 
#  sleuth:
#    sampler:
#      probability: 1.0 # 设置采样率为100%
  application:
    name: bigstock-schedule
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://43.153.144.80:31482/bstock
    username: bstockuser
    password: postgresql
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      leak-detection-threshold: 10000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true  
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true     
  redis:
    host: 43.153.144.80
    lettuce:
      pool:
        max-active: 200
        max-idle: 500
        min-idle: 10
        max-wait: 100000
    port: 32666      
logging:
  config: classpath:logback.xml
  
springdoc:
  api-docs:
    path: /schedule/swagger/v3/api-docs  
  swagger-ui:
    path: /schedule/swagger/swagger-ui.html
    enable: true
    supportHeaderParams: true
    
schedule:
  task:
    scheduling:
      cron:
        expression: 
          grasp-stock-price: "0 */40 * * * *"
          grasp-securitiesfirms-dayoperate: "0 */30 * * * *"
          update-shareholder-structure: "0 */30 * * * *"
          update-stock-info: "0 */30 * * * *"
          update-margin-trading:  "0 */30 * * * *"
          update-threeInsti: "0 30 18 * * *"
          update-monthlyRevenue: "0 0 8 * * SUN"
      similiar-search-reload: https://bigstock-similiarearch.zeabur.app/cache/reload
  chromeDriverPath:
    windows: 
      active: true	
      path: D:/bigStock/backend/group/schedule/src/main/resources/chrome-driver/chromedriver-win64/chromedriver-win64/chromedriver.exe
    linux:
       active: false
       driver-path: 1111
     #  chrome-path: ${CHROME_LINUX_PATH}	
    download-path: D:\bigStock\Downloads
  tdccQryStockUrl: https://www.tdcc.com.tw/portal/zh/smWeb/qryStock
  overTheCounterUrl: https://mops.twse.com.tw/mops/web/t51sb01
  manual-date-range:
    tpex-baseurl: https://www.tpex.org.tw/www/zh-tw/afterTrading/tradingStock
    search-start-date: 2025-10-05
    search-end-date: 2025-12-07
     # date格式 yyyyMMdd 
    twse-baseurl: https://www.twse.com.tw/rwd/zh/afterTrading/STOCK_DAY?date=%1s&stockNo=%2s&response=json&_=1730439477455    
    
   