server:
  port: 28081
  shutdown: graceful
spring:
  application:
    name: bigstock-schedule
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500 
  datasource:
    url: jdbc:postgresql://127.0.0.1:15432/bstock
    username: bstockuser
    password: postgresql
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true    
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 200
        max-idle: 500
        min-idle: 10
        max-wait: 100000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: rabbitmq
    virtual-host: /
    pool:
      channelCacheSize: 5          
logging:
  config: classpath:logback.xml

schedule:
  bpython-url: http://127.0.0.1:8000/captcha/
  credentials-pathl: D:\GOOGLE_APPLICATION_CREDENTIALS\api-project-488164973892-240337ff54fe.json
  task:
    scheduling:
      cron:
        expression: 
          grasp-stock-price: "0 */40 * * * *"
          grasp-securitiesfirms-dayoperate: "0 */30 * * * *"
          update-shareholder-structure: "0 */30 * * * *"
          update-stock-info: "0 */30 * * * *"
          update-margin-trading:  "0 */30 * * * *"
  chromeDriverPath:
    windows: 
      active: true	
      path: D:/bigStock/backend/group/schedule/src/main/resources/chrome-driver/chromedriver-win64/chromedriver-win64/chromedriver.exe
    linux:
       active: false
       driver-path: 1111
     #  chrome-path: ${CHROME_LINUX_PATH}	
    download-path: D:\bigStock\Downloads
  tdccQryStockUrl: https://www.tdcc.com.tw/portal/zh/smWeb/qryStock
  overTheCounterUrl: https://mops.twse.com.tw/mops/web/t51sb01
  manual-date-range:
    tpex-baseurl: https://www.tpex.org.tw/www/zh-tw/afterTrading/tradingStock
    search-start-date: 2025-04-05
    search-end-date: 2025-06-11
     # date格式 yyyyMMdd 
    twse-baseurl: https://www.twse.com.tw/rwd/zh/afterTrading/STOCK_DAY?date=%1s&stockNo=%2s&response=json&_=1730439477455
management:
  endpoints:
    web:
      exposure:
        include: "*" # 包含所有的Actuator端点，可以根据需要进行调整
  endpoint:
    health:
      show-details: always
  health:
    consul:
      enabled: true  
  tracing:
    enabled: true
    sampling:
      probability: 1.0  # 设置采样率为 100%
    export:
      otlp:
        enabled: true
        endpoint: http://localhost:14250  # Jaeger 的 OTLP 接收端点    
tracing:
  url: http://localhost:4317     
