version: '3.7'
services:
  bstock-postgresql:
    container_name: bstock-postgresql
    image: postgres:15-alpine
    ports:
      - "15432:5432"
    restart: always  
    volumes:
      - ./bstock_dump.sql:/tmp/bstock_dump.sql
      - ./bstock_dump.sql:/docker-entrypoint-initdb.d/02_bstock_dump.sql
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql
    shm_size: 1536m  
    networks:
      - big_stock_network   
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql 
      POSTGRES_SHARED_BUFFERS: "256MB"
    mem_limit: 1536m
  redis:
    image: redis:7.2.4
    container_name: redis
    restart: always 
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]
    networks:
      - big_stock_network  
    mem_limit: 512m  # 增加到 1G
    ##暫時移除
  #bigstock-python:
  #  build: ../../../BstockPython/src/
  #  restart: always 
  #  container_name: bigstock-python
  #  ports:
  #    - "8000:8000"   
  #  networks:
  #    - big_stock_network     
   
networks:
  big_stock_network:
    external: true
