server:
  port: 18081
  shutdown: graceful
  servlet:
    context-path: /schedule
spring:
  application:
    name: big-stcok-backend-schedule
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=bstock
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
  redis:
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 200
        max-idle: 500
        min-idle: 10
        max-wait: 100000
    port: 6379 
logging:
  config: classpath:logback.xml

schedule:
  task:
    scheduling:
      cron:
        expression: 
          grasp-stock-price: "0 0 20 ? * *"
          update-shareholder-structure: "0 0 8 ? * SUN"
          update-stock-info: "0 0 8 ? * SAT"
  chromeDriverPath:
    windows: 
      active: true	
      path: D:/sts/chromedriver-win64/chromedriver.exe
    linux:
       active: false
       path: DD	
  tdccQryStockUrl: https://www.tdcc.com.tw/portal/zh/smWeb/qryStock
  overTheCounterUrl: https://mops.twse.com.tw/mops/web/t51sb01
  stock-price:
    url:
      tpex: https://www.tpex.org.tw/web/stock/aftertrading/daily_close_quotes/stk_quote_result.php?l=zh-tw&d={dateString}&s=asc
      twse: https://www.twse.com.tw/pcversion/zh/exchangeReport/MI_INDEX
